title: "Najc"
description: "A Jekyll Blog"
author :
  name :  "Najc"
  email:  "18321965985@163.com"
  url  :  "https://www.najc.top"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

owner: "Najc"
year : "2021"
