# This is a basic workflow to help you get started with Actions

name: generate-news

# Controls when the action will run. 
on:
  schedule:
  - cron: "30 15 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          python-vesion: '3.7'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python3 scripts/get_daily_news.py
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages 
